"""Diagnosis pipeline: photos -> defects -> root causes."""
from typing import List, Dict, Optional
from pathlib import Path

from print_doctor.models import Diagnosis, Defect
from print_doctor.vision import (
    load_image,
    preprocess,
    ALL_DETECTORS,
)
from print_doctor.attribution import attribute_causes


def diagnose_photos(
    image_paths: List[str],
    hints: Optional[Dict[str, str]] = None,
    filenames: Optional[List[str]] = None,
) -> Diagnosis:
    """Diagnose a printed part from one or more photos.

    Args:
        image_paths: Paths to print photos (top/side/close-up)
        hints: Optional print parameter hints, e.g.
            {"material": "pla", "layer_height": "0.2",
             "temperature": "210", "retraction": "on"}
        filenames: Optional display name (defaults to first image name)

    Returns:
        Diagnosis with defects and ranked root causes
    """
    hints = hints or {}
    all_defects: List[Defect] = []

    for path in image_paths:
        img = load_image(str(path))
        gray, mask = preprocess(img)
        for detector in ALL_DETECTORS:
            try:
                defects = detector(img, mask)
                all_defects.extend(defects)
            except Exception:
                # A failing detector on one image should not kill the run
                continue

    # De-duplicate: keep the highest confidence for each defect type
    best: Dict[str, Defect] = {}
    for d in all_defects:
        key = d.type.value
        if key not in best or d.confidence > best[key].confidence:
            best[key] = d
    unique_defects = sorted(best.values(), key=lambda d: d.confidence, reverse=True)

    root_causes = attribute_causes(unique_defects, hints)

    display_name = filenames[0] if filenames else (
        Path(image_paths[0]).name if image_paths else "photos"
    )

    return Diagnosis(
        filename=display_name,
        defects=unique_defects,
        root_causes=root_causes,
        image_count=len(image_paths),
    )


def generate_diagnosis_report(diagnosis: Diagnosis) -> str:
    """Render a Markdown report for a Diagnosis."""
    lines = []
    lines.append(f"# Print Doctor Diagnosis: {diagnosis.filename}")
    lines.append(f"Images analyzed: {diagnosis.image_count}")
    lines.append("")

    if not diagnosis.defects:
        lines.append("## No Defects Detected")
        lines.append("The print looks healthy in the analyzed photos.")
        lines.append("")
    else:
        lines.append("## Detected Defects")
        lines.append("")
        for d in diagnosis.defects:
            lines.append(f"### {d.type.value} (confidence {d.confidence:.2f})")
            lines.append(f"- **Evidence:** {d.evidence}")
            lines.append("")

    if diagnosis.root_causes:
        lines.append("## Likely Root Causes")
        lines.append("")
        for i, rc in enumerate(diagnosis.root_causes, 1):
            lines.append(
                f"{i}. **{rc.cause}** (likelihood {rc.likelihood:.2f})"
            )
            lines.append(f"   - Fix: {rc.fix}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Print Doctor*")
    return "\n".join(lines)
