"""Diagnosis pipeline: photos -> defects -> root causes."""
from typing import List, Dict, Optional
from pathlib import Path

from print_doctor.models import Diagnosis, Defect
from print_doctor.vision import load_image
from print_doctor.attribution import attribute_causes


def _detect_on_image(img, use_ml: bool, classifier):
    """Run the defect detectors on a single image.

    Prefers the trained ML classifier when available (more reliable
    on real photos); falls back to the traditional CV detectors.
    """
    if use_ml and classifier is not None:
        from print_doctor.vision_ml import classify_photo
        return classify_photo(img, classifier=classifier)
    from print_doctor.vision import preprocess, ALL_DETECTORS
    gray, mask = preprocess(img)
    defects = []
    for detector in ALL_DETECTORS:
        try:
            defects.extend(detector(img, mask))
        except Exception:
            continue
    return defects


def diagnose_photos(
    image_paths: List[str],
    hints: Optional[Dict[str, str]] = None,
    filenames: Optional[List[str]] = None,
    use_ml: bool = True,
) -> Diagnosis:
    """Diagnose a printed part from one or more photos.

    Args:
        image_paths: Paths to print photos (top/side/close-up)
        hints: Optional print parameter hints, e.g.
            {"material": "pla", "layer_height": "0.2",
             "temperature": "210", "retraction": "on"}
        filenames: Optional display name (defaults to first image name)
        use_ml: Prefer the trained ML classifier (recommended). Falls
            back to traditional CV if the model file is missing.

    Returns:
        Diagnosis with defects and ranked root causes
    """
    hints = hints or {}

    # Try to load the ML classifier (best on real photos)
    classifier = None
    if use_ml:
        try:
            from print_doctor.vision_ml import DefectClassifier
            classifier = DefectClassifier()
        except Exception:
            classifier = None

    all_defects: List[Defect] = []
    all_regions = []
    for path in image_paths:
        img = load_image(str(path))
        all_defects.extend(_detect_on_image(img, use_ml, classifier))
        # Weakly-supervised localization: highlight where anomalies are
        try:
            from print_doctor.vision import preprocess, locate_defects
            gray, mask = preprocess(img)
            all_regions.extend(locate_defects(img, mask))
        except Exception:
            pass

    # De-duplicate: keep the highest confidence for each defect type
    best: Dict[str, Defect] = {}
    for d in all_defects:
        key = d.type.value
        if key not in best or d.confidence > best[key].confidence:
            best[key] = d
    unique_defects = sorted(best.values(), key=lambda d: d.confidence, reverse=True)

    root_causes = attribute_causes(unique_defects, hints)

    display_name = filenames[0] if filenames else (
        Path(image_paths[0]).name if image_paths else "photos"
    )

    return Diagnosis(
        filename=display_name,
        defects=unique_defects,
        root_causes=root_causes,
        image_count=len(image_paths),
        regions=all_regions,
    )


def generate_diagnosis_report(diagnosis: Diagnosis) -> str:
    """Render a Markdown report for a Diagnosis."""
    lines = []
    lines.append(f"# Print Doctor Diagnosis: {diagnosis.filename}")
    lines.append(f"Images analyzed: {diagnosis.image_count}")
    lines.append("")

    if not diagnosis.defects:
        lines.append("## No Defects Detected")
        lines.append("The print looks healthy in the analyzed photos.")
        lines.append("")
    else:
        lines.append("## Detected Defects")
        lines.append("")
        for d in diagnosis.defects:
            lines.append(f"### {d.type.value} (confidence {d.confidence:.2f})")
            lines.append(f"- **Evidence:** {d.evidence}")
            lines.append("")

    if diagnosis.regions:
        lines.append("## Anomaly Regions (localization)")
        lines.append("")
        lines.append("| # | Position (x,y,w,h) | Area | Score |")
        lines.append("|---|---|---|---|")
        for i, r in enumerate(diagnosis.regions, 1):
            lines.append(
                f"| {i} | ({r['x']}, {r['y']}, {r['w']}, {r['h']}) "
                f"| {r['area']} px | {r['score']} |"
            )
        lines.append("")
        lines.append("> Localization is best-effort: it highlights *where* "
                     "something is unusual, not *what* it is.")
        lines.append("")

    if diagnosis.root_causes:
        lines.append("## Likely Root Causes")
        lines.append("")
        for i, rc in enumerate(diagnosis.root_causes, 1):
            lines.append(
                f"{i}. **{rc.cause}** (likelihood {rc.likelihood:.2f})"
            )
            lines.append(f"   - Fix: {rc.fix}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Print Doctor*")
    return "\n".join(lines)
