"""Generate a customer-facing HTML quote sheet for a print job.

A printable, professional-looking quote with shop header, itemized
costs and terms. Distinct from the diagnostic HTML report - this is
the document a print shop sends to a customer.
"""
from typing import Optional

from print_doctor.models import MeshAnalysis, CostEstimate


def generate_quote_sheet(
    analysis: MeshAnalysis,
    estimate: Optional[CostEstimate],
    shop_name: str = "Print Doctor Shop",
    shop_contact: str = "",
    customer: str = "",
    quote_number: str = "",
    notes: str = "",
) -> str:
    """Build an HTML quote sheet.

    Args:
        analysis: Mesh analysis results
        estimate: Cost estimate (may be None -> cost section omitted)
        shop_name: Shop display name
        shop_contact: Contact line (phone/email/address)
        customer: Customer name/reference
        quote_number: Quote reference number
        notes: Optional free-text notes

    Returns:
        HTML document string
    """
    issues_count = len(analysis.issues)
    errors = sum(
        1 for i in analysis.issues if i.severity.value == "error"
    )

    cost_rows = ""
    if estimate:
        items = [
            ("Model analysis", f"{analysis.filename}"),
            ("Print time", f"{estimate.print_time_hours:.1f} h"),
            ("Material (weight)", f"{estimate.weight_grams:.1f} g"),
        ]
        if estimate.machine_cost:
            items += [
                ("Material cost", f"${estimate.material_cost:.2f}"),
                ("Electricity", f"${estimate.electricity_cost:.2f}"),
                ("Machine use", f"${estimate.machine_cost:.2f}"),
                ("Labor", f"${estimate.labor_cost:.2f}"),
                ("Waste allowance", f"${estimate.waste_cost:.2f}"),
            ]
        items += [
            ("Total cost", f"${estimate.total_cost:.2f}"),
        ]
        rows = "".join(
            f"<tr><td>{k}</td><td style='text-align:right'>{v}</td></tr>"
            for k, v in items
        )
        cost_rows = f"""
        <h2>Pricing</h2>
        <table class="quote">{rows}</table>
        <p class="total">Suggested retail price:
          <strong>${estimate.suggested_price:.2f}</strong></p>"""

    warning = ""
    if errors:
        warning = (
            "<p class='warn'>Note: this model has error-level issues "
            "and may not print reliably.</p>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Quote {quote_number} - {shop_name}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          max-width: 720px; margin: 2rem auto; padding: 0 1.5rem;
          color: #1a1a1a; }}
  .header {{ display: flex; justify-content: space-between;
             border-bottom: 3px solid #1a1a1a; padding-bottom: 1rem; }}
  h1 {{ margin: 0; font-size: 1.4rem; }}
  .shop {{ font-size: .9rem; color: #555; }}
  table.quote {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  table.quote td {{ padding: .5rem .4rem; border-bottom: 1px solid #ddd; }}
  .total {{ font-size: 1.1rem; margin-top: 1rem; }}
  .warn {{ color: #c62828; background: #fdecea; padding: .6rem 1rem;
           border-radius: 4px; }}
  .meta {{ font-size: .85rem; color: #555; }}
  .terms {{ margin-top: 2.5rem; font-size: .75rem; color: #888;
             border-top: 1px solid #ddd; padding-top: .8rem; }}
</style>
</head>
<body>
<div class="header">
  <div>
    <h1>{shop_name}</h1>
    <div class="shop">{shop_contact}</div>
  </div>
  <div class="meta">
    <div><strong>Quote</strong> {quote_number or '-'}</div>
    <div><strong>Customer</strong> {customer or '-'}</div>
  </div>
</div>

<h2>Quote Summary</h2>
<table class="quote">
  <tr><td>Part</td><td style="text-align:right">{analysis.filename}</td></tr>
  <tr><td>Printability score</td><td style="text-align:right">{analysis.score:.1f}/100</td></tr>
  <tr><td>Print issues</td><td style="text-align:right">{issues_count} ({errors} critical)</td></tr>
  <tr><td>Volume</td><td style="text-align:right">{analysis.volume / 1000.0:.2f} cm&sup3;</td></tr>
</table>
{warning}
{cost_rows}

{('<h2>Notes</h2><p>' + notes + '</p>') if notes else ''}

<div class="terms">
  Quote valid for 30 days. Prices exclude post-processing and shipping.
  Generated by Print Doctor.
</div>
</body>
</html>"""
