from typing import Optional
from print_doctor.models import MeshAnalysis, CostEstimate, Severity


def generate_report(
    analysis: MeshAnalysis,
    estimate: Optional[CostEstimate] = None,
) -> str:
    """Generate a Markdown report from analysis and cost estimate.

    Args:
        analysis: Mesh analysis results
        estimate: Optional cost estimate

    Returns:
        Markdown formatted report
    """
    lines = []

    lines.append(f"# Print Doctor Report: {analysis.filename}")
    lines.append("")

    lines.append(f"## Printability Score: {analysis.score:.1f}/100")
    lines.append("")

    lines.append("## Mesh Information")
    lines.append(f"- **Watertight:** {'yes' if analysis.is_watertight else 'no'}")
    lines.append(f"- **Manifold:** {'yes' if analysis.is_manifold else 'no'}")
    lines.append(f"- **Triangles:** {analysis.triangle_count:,}")
    lines.append(f"- **Volume:** {analysis.volume:.2f} cm3")
    lines.append(f"- **Surface Area:** {analysis.surface_area:.2f} cm2")
    lines.append(
        "- **Bounding Box:** "
        f"{analysis.bounding_box[0]:.1f} x {analysis.bounding_box[1]:.1f} "
        f"x {analysis.bounding_box[2]:.1f} mm"
    )
    lines.append("")

    if analysis.issues:
        lines.append("## Issues Found")
        lines.append("")

        severity_order = {
            Severity.ERROR: 0,
            Severity.WARNING: 1,
            Severity.INFO: 2,
        }
        sorted_issues = sorted(
            analysis.issues, key=lambda i: severity_order[i.severity]
        )

        for issue in sorted_issues:
            icon = (
                "ERROR" if issue.severity == Severity.ERROR
                else "WARNING" if issue.severity == Severity.WARNING
                else "INFO"
            )
            lines.append(f"### [{icon}] {issue.name}")
            lines.append(f"- **Description:** {issue.description}")
            lines.append(f"- **Location:** {issue.location}")
            lines.append(f"- **Suggestion:** {issue.suggestion}")
            lines.append("")
    else:
        lines.append("## No Issues Found")
        lines.append("Your model looks ready for printing!")
        lines.append("")

    if estimate:
        lines.append("## Cost Estimate")
        lines.append(f"- **Weight:** {estimate.weight_grams:.1f}g")
        lines.append(f"- **Print Time:** {estimate.print_time_hours:.1f} hours")
        lines.append(f"- **Material Cost:** ${estimate.material_cost:.2f}")
        lines.append(f"- **Electricity Cost:** ${estimate.electricity_cost:.2f}")
        lines.append(f"- **Total Cost:** ${estimate.total_cost:.2f}")
        lines.append(f"- **Suggested Price:** ${estimate.suggested_price:.2f}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Print Doctor*")

    return "\n".join(lines)
