from typing import Optional
from print_doctor.models import MeshAnalysis, CostEstimate, Severity


def generate_report(
    analysis: MeshAnalysis,
    estimate: Optional[CostEstimate] = None,
) -> str:
    """Generate a Markdown report from analysis and cost estimate.

    Args:
        analysis: Mesh analysis results
        estimate: Optional cost estimate

    Returns:
        Markdown formatted report
    """
    lines = []

    lines.append(f"# Print Doctor Report: {analysis.filename}")
    lines.append("")

    lines.append(f"## Printability Score: {analysis.score:.1f}/100")
    lines.append("")

    lines.append("## Mesh Information")
    lines.append(f"- **Watertight:** {'yes' if analysis.is_watertight else 'no'}")
    lines.append(f"- **Manifold:** {'yes' if analysis.is_manifold else 'no'}")
    lines.append(f"- **Triangles:** {analysis.triangle_count:,}")
    lines.append(f"- **Volume:** {analysis.volume / 1000.0:.2f} cm3")
    lines.append(f"- **Surface Area:** {analysis.surface_area / 100.0:.2f} cm2")
    lines.append(
        "- **Bounding Box:** "
        f"{analysis.bounding_box[0]:.1f} x {analysis.bounding_box[1]:.1f} "
        f"x {analysis.bounding_box[2]:.1f} mm"
    )
    lines.append("")

    if analysis.issues:
        lines.append("## Issues Found")
        lines.append("")

        severity_order = {
            Severity.ERROR: 0,
            Severity.WARNING: 1,
            Severity.INFO: 2,
        }
        sorted_issues = sorted(
            analysis.issues, key=lambda i: severity_order[i.severity]
        )

        for issue in sorted_issues:
            icon = (
                "ERROR" if issue.severity == Severity.ERROR
                else "WARNING" if issue.severity == Severity.WARNING
                else "INFO"
            )
            lines.append(f"### [{icon}] {issue.name}")
            lines.append(f"- **Description:** {issue.description}")
            lines.append(f"- **Location:** {issue.location}")
            lines.append(f"- **Suggestion:** {issue.suggestion}")
            lines.append("")
    else:
        lines.append("## No Issues Found")
        lines.append("Your model looks ready for printing!")
        lines.append("")

    if estimate:
        lines.append("## Cost Estimate")
        lines.append(f"- **Weight:** {estimate.weight_grams:.1f}g")
        lines.append(f"- **Print Time:** {estimate.print_time_hours:.1f} hours")
        lines.append(f"- **Material Cost:** ${estimate.material_cost:.2f}")
        lines.append(f"- **Electricity Cost:** ${estimate.electricity_cost:.2f}")
        if estimate.machine_cost:
            lines.append(f"- **Machine Depreciation:** ${estimate.machine_cost:.2f}")
            lines.append(f"- **Labor Cost:** ${estimate.labor_cost:.2f}")
            lines.append(f"- **Waste Allowance:** ${estimate.waste_cost:.2f}")
        lines.append(f"- **Total Cost:** ${estimate.total_cost:.2f}")
        lines.append(f"- **Suggested Price:** ${estimate.suggested_price:.2f}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Print Doctor*")

    return "\n".join(lines)


def generate_html_report(
    analysis: MeshAnalysis,
    estimate: Optional[CostEstimate] = None,
) -> str:
    """Generate a standalone HTML report with inline CSS.

    Args:
        analysis: Mesh analysis results
        estimate: Optional cost estimate

    Returns:
        HTML document string
    """
    score = analysis.score
    score_color = "#2e7d32" if score >= 80 else "#f9a825" if score >= 60 else "#c62828"

    issue_rows = []
    if analysis.issues:
        for i in analysis.issues:
            sev = i.severity.value
            color = {"error": "#c62828", "warning": "#f9a825", "info": "#1565c0"}[sev]
            issue_rows.append(f"""
                <div class="issue" style="border-left:4px solid {color}">
                  <h4 style="margin:0 0 6px;color:{color}">{sev.upper()}: {i.name}</h4>
                  <p><strong>Description:</strong> {i.description}</p>
                  <p><strong>Location:</strong> {i.location}</p>
                  <p><strong>Suggestion:</strong> {i.suggestion}</p>
                </div>""")
    else:
        issue_rows.append(
            '<p class="ok" style="color:#2e7d32">No issues found - model looks ready to print.</p>'
        )

    cost_block = ""
    if estimate:
        cost_rows = [
            ("Weight", f"{estimate.weight_grams:.1f} g"),
            ("Print time", f"{estimate.print_time_hours:.1f} h"),
            ("Material", f"${estimate.material_cost:.2f}"),
            ("Electricity", f"${estimate.electricity_cost:.2f}"),
        ]
        if estimate.machine_cost:
            cost_rows += [
                ("Machine depreciation", f"${estimate.machine_cost:.2f}"),
                ("Labor", f"${estimate.labor_cost:.2f}"),
                ("Waste allowance", f"${estimate.waste_cost:.2f}"),
            ]
        cost_rows += [
            ("Total cost", f"${estimate.total_cost:.2f}"),
            ("Suggested price", f"<strong>${estimate.suggested_price:.2f}</strong>"),
        ]
        rows = "".join(
            f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in cost_rows
        )
        cost_block = f"""
        <h3>Cost Estimate</h3>
        <table>{rows}</table>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Print Doctor Report - {analysis.filename}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          max-width: 800px; margin: 2rem auto; padding: 0 1rem;
          color: #212121; line-height: 1.5; }}
  h1 {{ border-bottom: 2px solid #e0e0e0; padding-bottom: .5rem; }}
  .score {{ font-size: 2.2rem; font-weight: 700; color: {score_color}; }}
  table {{ border-collapse: collapse; width: 100%; margin: .5rem 0 1.5rem; }}
  td {{ padding: .35rem .6rem; border-bottom: 1px solid #eee; }}
  .issue {{ background: #fafafa; border-radius: 6px; padding: .8rem 1rem;
            margin: .6rem 0; }}
  footer {{ margin-top: 2rem; color: #9e9e9e; font-size: .85rem; }}
</style>
</head>
<body>
<h1>Print Doctor Report: {analysis.filename}</h1>
<p class="score">{score:.1f}/100</p>

<h3>Mesh Information</h3>
<table>
  <tr><td>Watertight</td><td>{'yes' if analysis.is_watertight else 'no'}</td></tr>
  <tr><td>Manifold</td><td>{'yes' if analysis.is_manifold else 'no'}</td></tr>
  <tr><td>Triangles</td><td>{analysis.triangle_count:,}</td></tr>
  <tr><td>Volume</td><td>{analysis.volume / 1000.0:.2f} cm&sup3;</td></tr>
  <tr><td>Surface area</td><td>{analysis.surface_area / 100.0:.2f} cm&sup2;</td></tr>
  <tr><td>Bounding box</td><td>{analysis.bounding_box[0]:.1f} x {analysis.bounding_box[1]:.1f} x {analysis.bounding_box[2]:.1f} mm</td></tr>
</table>

<h3>Issues Found</h3>
{''.join(issue_rows)}

{cost_block}
<footer>Generated by Print Doctor</footer>
</body>
</html>"""


def generate_json_report(
    analysis: MeshAnalysis,
    estimate: Optional[CostEstimate] = None,
) -> str:
    """Generate a machine-readable JSON report.

    The schema is stable for integration (batch quotes, APIs).

    Args:
        analysis: Mesh analysis results
        estimate: Optional cost estimate

    Returns:
        JSON string
    """
    import json

    data = {
        "schema_version": 1,
        "filename": analysis.filename,
        "printability_score": round(analysis.score, 2),
        "mesh": {
            "watertight": analysis.is_watertight,
            "manifold": analysis.is_manifold,
            "triangle_count": analysis.triangle_count,
            "volume_cm3": round(analysis.volume / 1000.0, 3),
            "surface_area_cm2": round(analysis.surface_area / 100.0, 3),
            "bounding_box_mm": [round(v, 2) for v in analysis.bounding_box],
        },
        "issues": [
            {
                "name": i.name,
                "severity": i.severity.value,
                "description": i.description,
                "location": i.location,
                "suggestion": i.suggestion,
            }
            for i in analysis.issues
        ],
    }
    if estimate is not None:
        data["cost"] = {
            "weight_grams": round(estimate.weight_grams, 2),
            "print_time_hours": round(estimate.print_time_hours, 2),
            "material_cost": round(estimate.material_cost, 4),
            "electricity_cost": round(estimate.electricity_cost, 4),
            "machine_cost": round(estimate.machine_cost, 4),
            "labor_cost": round(estimate.labor_cost, 4),
            "waste_cost": round(estimate.waste_cost, 4),
            "total_cost": round(estimate.total_cost, 4),
            "suggested_price": round(estimate.suggested_price, 4),
        }
    return json.dumps(data, indent=2)
