"""Tests for G-code analysis (layers, extrusion, progress)."""
from print_doctor.gcode import parse_gcode, parse_gcode_file

ORCA_GCODE = """; generated by OrcaSlicer
;LAYER_CHANGE
;Z:0.2
G1 Z0.2
G1 X10 Y10 E0.1
;LAYER_CHANGE
;Z:0.4
G1 Z0.4
G1 X20 Y20 E0.3
;LAYER_CHANGE
;Z:0.6
G1 Z0.6
G1 X30 Y30 E0.5
"""

BAMBU_GCODE = """; generated by BambuStudio
;LAYER:0
G1 Z0.2 E0.1
;LAYER:1
G1 Z0.4 E0.3
;LAYER:2
G1 Z0.6 E0.5
"""


def test_parse_orca_layers():
    a = parse_gcode(ORCA_GCODE)
    assert a.layer_count == 3
    assert a.total_extruded == 0.9
    assert a.layers[0].z == 0.2
    assert a.layers[2].z == 0.6
    assert abs(a.layers[1].e_volume - 0.3) < 1e-9


def test_parse_bambu_layers():
    a = parse_gcode(BAMBU_GCODE)
    assert a.layer_count == 3
    assert a.layers[0].number == 0
    assert a.layers[1].number == 1
    assert a.layers[2].number == 2
    assert a.total_extruded == 0.9


def test_progress_at():
    a = parse_gcode(ORCA_GCODE)
    assert a.progress_at(0.0) == 0.0
    assert abs(a.progress_at(0.45) - 0.5) < 1e-9
    assert a.progress_at(0.9) == 1.0
    assert a.progress_at(99.0) == 1.0  # clamped


def test_layer_at():
    a = parse_gcode(ORCA_GCODE)
    # 层区间: [0,0.1], [0.1,0.4], [0.4,0.9]
    assert a.layer_at(0.05).number == 0
    assert a.layer_at(0.25).number == 1
    assert a.layer_at(0.45).number == 2
    assert a.layer_at(99.0) is None
    assert a.layer_at(0.05).number == 0
    assert a.layer_at(99.0) is None


def test_parse_empty():
    a = parse_gcode("; nothing here\nG1 X0 Y0\n")
    assert a.layer_count == 0
    assert a.total_extruded == 0.0
    assert a.progress_at(0.0) == 0.0


def test_parse_file(tmp_path):
    f = tmp_path / "model.gcode"
    f.write_text(ORCA_GCODE)
    a = parse_gcode_file(str(f))
    assert a.layer_count == 3
    assert a.filename == str(f)
